'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'Este código fuente fue generado automáticamente por xsd, Versión=4.6.1055.0.
'
Namespace SatV33_C

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.sat.gob.mx/cfd/3", IsNullable:=False)> _
    Partial Public Class Comprobante

        Private cfdiRelacionadosField As ComprobanteCfdiRelacionados

        Private emisorField As ComprobanteEmisor

        Private receptorField As ComprobanteReceptor

        Private conceptosField() As ComprobanteConcepto

        Private impuestosField As ComprobanteImpuestos

        Private complementoField() As ComprobanteComplemento

        Private addendaField As ComprobanteAddenda

        Private versionField As String

        Private serieField As String

        Private folioField As String

        Private fechaField As Date

        Private selloField As String

        Private formaPagoField As String

        Private noCertificadoField As String

        Private certificadoField As String

        Private condicionesDePagoField As String

        Private subTotalField As Decimal

        Private descuentoField As Decimal

        Private descuentoFieldSpecified As Boolean

        Private monedaField As String

        Private tipoCambioField As Decimal

        Private tipoCambioFieldSpecified As Boolean

        Private totalField As Decimal

        Private tipoDeComprobanteField As String

        Private metodoPagoField As String

        Private lugarExpedicionField As String

        Private confirmacionField As String

        Public Sub New()
            MyBase.New()
            Me.versionField = "3.3"
        End Sub

        '''<remarks/>
        Public Property CfdiRelacionados() As ComprobanteCfdiRelacionados
            Get
                Return Me.cfdiRelacionadosField
            End Get
            Set(ByVal value As ComprobanteCfdiRelacionados)
                Me.cfdiRelacionadosField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Emisor() As ComprobanteEmisor
            Get
                Return Me.emisorField
            End Get
            Set(ByVal value As ComprobanteEmisor)
                Me.emisorField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Receptor() As ComprobanteReceptor
            Get
                Return Me.receptorField
            End Get
            Set(ByVal value As ComprobanteReceptor)
                Me.receptorField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Concepto", IsNullable:=False)> _
        Public Property Conceptos() As ComprobanteConcepto()
            Get
                Return Me.conceptosField
            End Get
            Set(ByVal value As ComprobanteConcepto())
                Me.conceptosField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Impuestos() As ComprobanteImpuestos
            Get
                Return Me.impuestosField
            End Get
            Set(ByVal value As ComprobanteImpuestos)
                Me.impuestosField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Complemento")> _
        Public Property Complemento() As ComprobanteComplemento()
            Get
                Return Me.complementoField
            End Get
            Set(ByVal value As ComprobanteComplemento())
                Me.complementoField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Addenda() As ComprobanteAddenda
            Get
                Return Me.addendaField
            End Get
            Set(ByVal value As ComprobanteAddenda)
                Me.addendaField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Version() As String
            Get
                Return Me.versionField
            End Get
            Set(ByVal value As String)
                Me.versionField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Serie() As String
            Get
                Return Me.serieField
            End Get
            Set(ByVal value As String)
                Me.serieField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Folio() As String
            Get
                Return Me.folioField
            End Get
            Set(ByVal value As String)
                Me.folioField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set(ByVal value As Date)
                Me.fechaField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Sello() As String
            Get
                Return Me.selloField
            End Get
            Set(ByVal value As String)
                Me.selloField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property FormaPago() As String
            Get
                Return Me.formaPagoField
            End Get
            Set(ByVal value As String)
                Me.formaPagoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property NoCertificado() As String
            Get
                Return Me.noCertificadoField
            End Get
            Set(ByVal value As String)
                Me.noCertificadoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Certificado() As String
            Get
                Return Me.certificadoField
            End Get
            Set(ByVal value As String)
                Me.certificadoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property CondicionesDePago() As String
            Get
                Return Me.condicionesDePagoField
            End Get
            Set(ByVal value As String)
                Me.condicionesDePagoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property SubTotal() As Decimal
            Get
                Return Me.subTotalField
            End Get
            Set(ByVal value As Decimal)
                Me.subTotalField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Descuento() As Decimal
            Get
                Return Me.descuentoField
            End Get
            Set(ByVal value As Decimal)
                Me.descuentoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property DescuentoSpecified() As Boolean
            Get
                Return Me.descuentoFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.descuentoFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Moneda() As String
            Get
                Return Me.monedaField
            End Get
            Set(ByVal value As String)
                Me.monedaField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property TipoCambio() As Decimal
            Get
                Return Me.tipoCambioField
            End Get
            Set(ByVal value As Decimal)
                Me.tipoCambioField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property TipoCambioSpecified() As Boolean
            Get
                Return Me.tipoCambioFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.tipoCambioFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Total() As Decimal
            Get
                Return Me.totalField
            End Get
            Set(ByVal value As Decimal)
                Me.totalField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property TipoDeComprobante() As String
            Get
                Return Me.tipoDeComprobanteField
            End Get
            Set(ByVal value As String)
                Me.tipoDeComprobanteField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property MetodoPago() As String
            Get
                Return Me.metodoPagoField
            End Get
            Set(ByVal value As String)
                Me.metodoPagoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property LugarExpedicion() As String
            Get
                Return Me.lugarExpedicionField
            End Get
            Set(ByVal value As String)
                Me.lugarExpedicionField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Confirmacion() As String
            Get
                Return Me.confirmacionField
            End Get
            Set(ByVal value As String)
                Me.confirmacionField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteCfdiRelacionados

        Private cfdiRelacionadoField() As ComprobanteCfdiRelacionadosCfdiRelacionado

        Private tipoRelacionField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("CfdiRelacionado")> _
        Public Property CfdiRelacionado() As ComprobanteCfdiRelacionadosCfdiRelacionado()
            Get
                Return Me.cfdiRelacionadoField
            End Get
            Set(ByVal value As ComprobanteCfdiRelacionadosCfdiRelacionado())
                Me.cfdiRelacionadoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property TipoRelacion() As String
            Get
                Return Me.tipoRelacionField
            End Get
            Set(ByVal value As String)
                Me.tipoRelacionField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteCfdiRelacionadosCfdiRelacionado

        Private uUIDField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property UUID() As String
            Get
                Return Me.uUIDField
            End Get
            Set(ByVal value As String)
                Me.uUIDField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteEmisor

        Private rfcField As String

        Private nombreField As String

        Private regimenFiscalField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Rfc() As String
            Get
                Return Me.rfcField
            End Get
            Set(ByVal value As String)
                Me.rfcField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set(ByVal value As String)
                Me.nombreField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property RegimenFiscal() As String
            Get
                Return Me.regimenFiscalField
            End Get
            Set(ByVal value As String)
                Me.regimenFiscalField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteReceptor

        Private rfcField As String

        Private nombreField As String

        Private residenciaFiscalField As String

        Private numRegIdTribField As String

        Private usoCFDIField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Rfc() As String
            Get
                Return Me.rfcField
            End Get
            Set(ByVal value As String)
                Me.rfcField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set(ByVal value As String)
                Me.nombreField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property ResidenciaFiscal() As String
            Get
                Return Me.residenciaFiscalField
            End Get
            Set(ByVal value As String)
                Me.residenciaFiscalField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property NumRegIdTrib() As String
            Get
                Return Me.numRegIdTribField
            End Get
            Set(ByVal value As String)
                Me.numRegIdTribField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property UsoCFDI() As String
            Get
                Return Me.usoCFDIField
            End Get
            Set(ByVal value As String)
                Me.usoCFDIField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteConcepto

        Private impuestosField As ComprobanteConceptoImpuestos

        Private informacionAduaneraField() As ComprobanteConceptoInformacionAduanera

        Private cuentaPredialField As ComprobanteConceptoCuentaPredial

        Private complementoConceptoField As ComprobanteConceptoComplementoConcepto

        Private parteField() As ComprobanteConceptoParte

        Private claveProdServField As String

        Private noIdentificacionField As String

        Private cantidadField As Decimal

        Private claveUnidadField As String

        Private unidadField As String

        Private descripcionField As String

        Private valorUnitarioField As Decimal

        Private importeField As Decimal

        Private descuentoField As Decimal

        Private descuentoFieldSpecified As Boolean

        '''<remarks/>
        Public Property Impuestos() As ComprobanteConceptoImpuestos
            Get
                Return Me.impuestosField
            End Get
            Set(ByVal value As ComprobanteConceptoImpuestos)
                Me.impuestosField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("InformacionAduanera")> _
        Public Property InformacionAduanera() As ComprobanteConceptoInformacionAduanera()
            Get
                Return Me.informacionAduaneraField
            End Get
            Set(ByVal value As ComprobanteConceptoInformacionAduanera())
                Me.informacionAduaneraField = value
            End Set
        End Property

        '''<remarks/>
        Public Property CuentaPredial() As ComprobanteConceptoCuentaPredial
            Get
                Return Me.cuentaPredialField
            End Get
            Set(ByVal value As ComprobanteConceptoCuentaPredial)
                Me.cuentaPredialField = value
            End Set
        End Property

        '''<remarks/>
        Public Property ComplementoConcepto() As ComprobanteConceptoComplementoConcepto
            Get
                Return Me.complementoConceptoField
            End Get
            Set(ByVal value As ComprobanteConceptoComplementoConcepto)
                Me.complementoConceptoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Parte")> _
        Public Property Parte() As ComprobanteConceptoParte()
            Get
                Return Me.parteField
            End Get
            Set(ByVal value As ComprobanteConceptoParte())
                Me.parteField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property ClaveProdServ() As String
            Get
                Return Me.claveProdServField
            End Get
            Set(ByVal value As String)
                Me.claveProdServField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property NoIdentificacion() As String
            Get
                Return Me.noIdentificacionField
            End Get
            Set(ByVal value As String)
                Me.noIdentificacionField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set(ByVal value As Decimal)
                Me.cantidadField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property ClaveUnidad() As String
            Get
                Return Me.claveUnidadField
            End Get
            Set(ByVal value As String)
                Me.claveUnidadField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Unidad() As String
            Get
                Return Me.unidadField
            End Get
            Set(ByVal value As String)
                Me.unidadField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set(ByVal value As String)
                Me.descripcionField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property ValorUnitario() As Decimal
            Get
                Return Me.valorUnitarioField
            End Get
            Set(ByVal value As Decimal)
                Me.valorUnitarioField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Importe() As Decimal
            Get
                Return Me.importeField
            End Get
            Set(ByVal value As Decimal)
                Me.importeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Descuento() As Decimal
            Get
                Return Me.descuentoField
            End Get
            Set(ByVal value As Decimal)
                Me.descuentoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property DescuentoSpecified() As Boolean
            Get
                Return Me.descuentoFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.descuentoFieldSpecified = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteConceptoImpuestos

        Private trasladosField() As ComprobanteConceptoImpuestosTraslado

        Private retencionesField() As ComprobanteConceptoImpuestosRetencion

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Traslado", IsNullable:=False)> _
        Public Property Traslados() As ComprobanteConceptoImpuestosTraslado()
            Get
                Return Me.trasladosField
            End Get
            Set(ByVal value As ComprobanteConceptoImpuestosTraslado())
                Me.trasladosField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Retencion", IsNullable:=False)> _
        Public Property Retenciones() As ComprobanteConceptoImpuestosRetencion()
            Get
                Return Me.retencionesField
            End Get
            Set(ByVal value As ComprobanteConceptoImpuestosRetencion())
                Me.retencionesField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteConceptoImpuestosTraslado

        Private baseField As Decimal

        Private impuestoField As String

        Private tipoFactorField As String

        Private tasaOCuotaField As Decimal

        Private tasaOCuotaFieldSpecified As Boolean

        Private importeField As Decimal

        Private importeFieldSpecified As Boolean

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Base() As Decimal
            Get
                Return Me.baseField
            End Get
            Set(ByVal value As Decimal)
                Me.baseField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Impuesto() As String
            Get
                Return Me.impuestoField
            End Get
            Set(ByVal value As String)
                Me.impuestoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property TipoFactor() As String
            Get
                Return Me.tipoFactorField
            End Get
            Set(ByVal value As String)
                Me.tipoFactorField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property TasaOCuota() As Decimal
            Get
                Return Me.tasaOCuotaField
            End Get
            Set(ByVal value As Decimal)
                Me.tasaOCuotaField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property TasaOCuotaSpecified() As Boolean
            Get
                Return Me.tasaOCuotaFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.tasaOCuotaFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Importe() As Decimal
            Get
                Return Me.importeField
            End Get
            Set(ByVal value As Decimal)
                Me.importeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ImporteSpecified() As Boolean
            Get
                Return Me.importeFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.importeFieldSpecified = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteConceptoImpuestosRetencion

        Private baseField As Decimal

        Private impuestoField As String

        Private tipoFactorField As String

        Private tasaOCuotaField As Decimal

        Private importeField As Decimal

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Base() As Decimal
            Get
                Return Me.baseField
            End Get
            Set(ByVal value As Decimal)
                Me.baseField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Impuesto() As String
            Get
                Return Me.impuestoField
            End Get
            Set(ByVal value As String)
                Me.impuestoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property TipoFactor() As String
            Get
                Return Me.tipoFactorField
            End Get
            Set(ByVal value As String)
                Me.tipoFactorField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property TasaOCuota() As Decimal
            Get
                Return Me.tasaOCuotaField
            End Get
            Set(ByVal value As Decimal)
                Me.tasaOCuotaField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Importe() As Decimal
            Get
                Return Me.importeField
            End Get
            Set(ByVal value As Decimal)
                Me.importeField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteConceptoInformacionAduanera

        Private numeroPedimentoField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property NumeroPedimento() As String
            Get
                Return Me.numeroPedimentoField
            End Get
            Set(ByVal value As String)
                Me.numeroPedimentoField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteConceptoCuentaPredial

        Private numeroField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Numero() As String
            Get
                Return Me.numeroField
            End Get
            Set(ByVal value As String)
                Me.numeroField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteConceptoComplementoConcepto

        Private anyField() As System.Xml.XmlElement

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set(ByVal value As System.Xml.XmlElement())
                Me.anyField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteConceptoParte

        Private informacionAduaneraField() As ComprobanteConceptoParteInformacionAduanera

        Private claveProdServField As String

        Private noIdentificacionField As String

        Private cantidadField As Decimal

        Private unidadField As String

        Private descripcionField As String

        Private valorUnitarioField As Decimal

        Private valorUnitarioFieldSpecified As Boolean

        Private importeField As Decimal

        Private importeFieldSpecified As Boolean

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("InformacionAduanera")> _
        Public Property InformacionAduanera() As ComprobanteConceptoParteInformacionAduanera()
            Get
                Return Me.informacionAduaneraField
            End Get
            Set(ByVal value As ComprobanteConceptoParteInformacionAduanera())
                Me.informacionAduaneraField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property ClaveProdServ() As String
            Get
                Return Me.claveProdServField
            End Get
            Set(ByVal value As String)
                Me.claveProdServField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property NoIdentificacion() As String
            Get
                Return Me.noIdentificacionField
            End Get
            Set(ByVal value As String)
                Me.noIdentificacionField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set(ByVal value As Decimal)
                Me.cantidadField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Unidad() As String
            Get
                Return Me.unidadField
            End Get
            Set(ByVal value As String)
                Me.unidadField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set(ByVal value As String)
                Me.descripcionField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property ValorUnitario() As Decimal
            Get
                Return Me.valorUnitarioField
            End Get
            Set(ByVal value As Decimal)
                Me.valorUnitarioField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ValorUnitarioSpecified() As Boolean
            Get
                Return Me.valorUnitarioFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.valorUnitarioFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Importe() As Decimal
            Get
                Return Me.importeField
            End Get
            Set(ByVal value As Decimal)
                Me.importeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ImporteSpecified() As Boolean
            Get
                Return Me.importeFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.importeFieldSpecified = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteConceptoParteInformacionAduanera

        Private numeroPedimentoField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property NumeroPedimento() As String
            Get
                Return Me.numeroPedimentoField
            End Get
            Set(ByVal value As String)
                Me.numeroPedimentoField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteImpuestos

        Private retencionesField() As ComprobanteImpuestosRetencion

        Private trasladosField() As ComprobanteImpuestosTraslado

        Private totalImpuestosRetenidosField As Decimal

        Private totalImpuestosRetenidosFieldSpecified As Boolean

        Private totalImpuestosTrasladadosField As Decimal

        Private totalImpuestosTrasladadosFieldSpecified As Boolean

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Retencion", IsNullable:=False)> _
        Public Property Retenciones() As ComprobanteImpuestosRetencion()
            Get
                Return Me.retencionesField
            End Get
            Set(ByVal value As ComprobanteImpuestosRetencion())
                Me.retencionesField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Traslado", IsNullable:=False)> _
        Public Property Traslados() As ComprobanteImpuestosTraslado()
            Get
                Return Me.trasladosField
            End Get
            Set(ByVal value As ComprobanteImpuestosTraslado())
                Me.trasladosField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property TotalImpuestosRetenidos() As Decimal
            Get
                Return Me.totalImpuestosRetenidosField
            End Get
            Set(ByVal value As Decimal)
                Me.totalImpuestosRetenidosField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property TotalImpuestosRetenidosSpecified() As Boolean
            Get
                Return Me.totalImpuestosRetenidosFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.totalImpuestosRetenidosFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property TotalImpuestosTrasladados() As Decimal
            Get
                Return Me.totalImpuestosTrasladadosField
            End Get
            Set(ByVal value As Decimal)
                Me.totalImpuestosTrasladadosField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property TotalImpuestosTrasladadosSpecified() As Boolean
            Get
                Return Me.totalImpuestosTrasladadosFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.totalImpuestosTrasladadosFieldSpecified = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteImpuestosRetencion

        Private impuestoField As String

        Private importeField As Decimal

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Impuesto() As String
            Get
                Return Me.impuestoField
            End Get
            Set(ByVal value As String)
                Me.impuestoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Importe() As Decimal
            Get
                Return Me.importeField
            End Get
            Set(ByVal value As Decimal)
                Me.importeField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteImpuestosTraslado

        Private impuestoField As String

        Private tipoFactorField As String

        Private tasaOCuotaField As Decimal

        Private importeField As Decimal

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Impuesto() As String
            Get
                Return Me.impuestoField
            End Get
            Set(ByVal value As String)
                Me.impuestoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property TipoFactor() As String
            Get
                Return Me.tipoFactorField
            End Get
            Set(ByVal value As String)
                Me.tipoFactorField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property TasaOCuota() As Decimal
            Get
                Return Me.tasaOCuotaField
            End Get
            Set(ByVal value As Decimal)
                Me.tasaOCuotaField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Importe() As Decimal
            Get
                Return Me.importeField
            End Get
            Set(ByVal value As Decimal)
                Me.importeField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteComplemento

        Private anyField() As System.Xml.XmlElement

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set(ByVal value As System.Xml.XmlElement())
                Me.anyField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")> _
    Partial Public Class ComprobanteAddenda

        Private anyField() As System.Xml.XmlElement

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set(ByVal value As System.Xml.XmlElement())
                Me.anyField = value
            End Set
        End Property
    End Class
End Namespace
